### ISSUE TITLE
IMM Review

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Retry#36]
Go through every item on the IP Maturity Matrix and ensure it is up to date, adding work items in any areas that could be improved

- [x] **Shared Engineering Standards**
- [x] **Coding Standards**
- [x] **Executable Specifications** #53
- [x] **Code Coverage**
- [ ] **Benchmarks** #54
- [x] **Reference Documentation**
- [x] **Design & Implementation Documentation** #55
- [x] **How-to Documentation** #56
- [x] **Date of Last IP Review**
- [x] **Framework Version**
- [x] **Associated Work Items** #57
- [x] **Source Code Availability**
- [x] **License**: Apache 2.0
- [x] **Production Use**
- [x] **Insights** #58
- [x] **Packaging** #59
- [x] **Deployment**
- [x] **Next IMM review** #60
